In [3]:
import numpy as np
import cv2

In [4]:
img=cv2.imread('Test.png')

In [8]:
cv2.imshow('Test',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Image Pointing

In [9]:
import cv2
import numpy as np
 
img = cv2.imread(r'C:\Users\angshuman\Desktop\Test\Test.png')
 
width, height = 250,350
pts1 = np.float32([[111,219],[287,188],[154,482],[352,440]])
pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix = cv2.getPerspectiveTransform(pts1,pts2)
imgOutput = cv2.warpPerspective(img,matrix,(width,height))
 
for x in range (0,4):
    cv2.circle(img,(pts1[x][0],pts1[x][1]),15,(0,255,0),cv2.FILLED)
 
cv2.imshow("Original Image ", img)
cv2.imshow("Output Image ", imgOutput)
cv2.waitKey(0)

<ipython-input-9-ad176e82a03d>:13: DeprecationWarning: an integer is required (got type numpy.float32).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  cv2.circle(img,(pts1[x][0],pts1[x][1]),15,(0,255,0),cv2.FILLED)


-1

### Clicking And finding coordinates in x,y

In [5]:
def mousePoints(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,y)
        
img=cv2.imread(r'C:\Users\angshuman\Desktop\Test\Test.png')
cv2.imshow('Test',img)
cv2.setMouseCallback('Test',mousePoints)
cv2.waitKey(0)

134 276
225 275
315 273
406 273
135 465
224 467
314 466
405 466


-1

### Mark on image 

In [5]:
import numpy as np
import cv2
circles=np.zeros((4,2),np.int)
counter=0

def mousePoints(event,x,y,flags,params):
    global counter
    if event == cv2.EVENT_LBUTTONDOWN:
        
        circles[counter]=x,y
        counter=counter+1
        print(circles)
    
img = cv2.imread(r'C:\Users\angshuman\Desktop\Test\Test.png')

while True:
    if counter==4:
        width, height = 250,350
        pts1 = np.float32([circles[0],circles[1],circles[2],circles[3]])
        pts2 = np.float32([[0,0],[width,0],[0,height],[width,height]])
        matrix = cv2.getPerspectiveTransform(pts1,pts2)
        imgOutput = cv2.warpPerspective(img,matrix,(width,height))
        cv2.imshow('Output',imgOutput)

    for x in range (0,4):
        cv2.circle(img,(circles[x][0],circles[x][1]),5,(0,255,0),cv2.FILLED)
 
        
    cv2.imshow('Test',img)
    cv2.setMouseCallback('Test',mousePoints)
    cv2.waitKey(0)
    
    if counter==4:
        cv2.destroyAllWindows()
        break
    


[[131 274]
 [  0   0]
 [  0   0]
 [  0   0]]
[[131 274]
 [133 467]
 [  0   0]
 [  0   0]]
[[131 274]
 [133 467]
 [268 465]
 [  0   0]]
[[131 274]
 [133 467]
 [268 465]
 [269 272]]


In [9]:
import numpy as np
import cv2
circles=np.zeros((8,2),np.int)
counter=0

def mousePoints(event,x,y,flags,params):
    global counter
    if event == cv2.EVENT_LBUTTONDOWN:
        
        circles[counter]=x,y
        counter=counter+1
        print(x,y)
while True:
    img=cv2.imread(r'C:\Users\angshuman\Desktop\Test\Test.png')
    cv2.imshow('Test',img)
    cv2.setMouseCallback('Test',mousePoints)
    cv2.waitKey(0)
    if counter==8:
        cv2.destroyAllWindows()
        break


134 276
228 274
315 274
401 274
133 465
226 466
314 466
404 467


IndexError: index 8 is out of bounds for axis 0 with size 8

In [2]:
print(circles)

[[134 274]
 [225 275]
 [312 272]
 [405 274]
 [134 465]
 [224 468]
 [315 466]
 [404 466]]


In [10]:
circles[0][1]

276